version: '3.6'   # Docker Engine release 18.02.0+

services:

  nginx:
    container_name: 'nginx'
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    links:
      - node
      - postgres
    ports:
      - 80:80
  node:
    container_name: 'node'
    build: .

  postgres:
    container_name: 'postgres'
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=%Euk6kBk   # Change this password!
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:

  postgres-data: